export const COURSE_CATEGORIES = [
  "Programming",
  "Design",
  "Business",
  "Marketing",
  "Personal Development",
  "IT & Software",
  "Office Productivity",
  "Photography",
  "Health & Fitness",
  "Music",
  "Teaching & Academics",
  "Finance & Accounting",
  "Data Science",
  "Web Development",
  "Mobile Apps",
  "Game Development",
  "Digital Marketing",
  "Graphic Design",
  "Video & Animation",
  "3D & Animation",
  "Lifestyle",
  "Language Learning",
  "Humanities",
  "Social Sciences",
  "Engineering",
  "Architecture",
  "Art & Crafts",
  "Beauty & Makeup",
  "Cooking",
  "DIY & Crafts",
  "Fashion",
  "Gardening",
  "Home Improvement",
  "Pet Care & Training",
  "Travel",
  "Other",
] as const;

export const COURSE_LEVEL = ["Beginner", "Medium", "Advance"] as const;

export type CourseCategory = (typeof COURSE_CATEGORIES)[number];
